---
extends:
  - "../.eslintrc.yml"

overrides:
  # Disable warning `require`/console-log on Node-js files
  - files:
      - node.api.js
      - static.config.js
    rules:
      "@typescript-eslint/no-var-requires": off
      "global-require": off
      "no-console": off

  # Disable extensions on scss files inside scss files
  - files:
      - "*.scss"
    rules:
      import/extensions:
        - warn
        - scss: never

  # Disable no-cycle warnings in utility files (unavoidable)
  - files:
      - "./src/utility/**/*.ts"
      - "./src/store/**/*.ts"
    rules:
      "import/no-cycle": off

  # Disable no-param-reassign warnings in store slices (using immer.js)
  - files:
      - "./src/store/slices/**/*.ts"
    rules:
      no-param-reassign: off

# ESLint Project Settings
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      directory": ./tsconfig.json
